# Generated by Django 4.1.5 on 2023-01-27 18:26

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Transacao",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "tipo",
                    models.CharField(
                        choices=[
                            ("Débito", "Deb"),
                            ("Boleto", "Bol"),
                            ("Financiamento", "Fin"),
                            ("Crédito", "Cre"),
                            ("Recebimento", "Rec"),
                            ("Vendas", "Ven"),
                            ("Recebimnto TED", "Ted"),
                            ("Recebimento DOC", "Doc"),
                            ("Aluguel", "Alu"),
                        ],
                        max_length=15,
                    ),
                ),
                ("data", models.DateField(max_length=8)),
                ("valor", models.FloatField()),
                ("cpf", models.CharField(max_length=11)),
                ("cartao", models.CharField(max_length=12)),
                ("hora", models.CharField(max_length=8)),
                ("dono_da_loja", models.CharField(max_length=14)),
                ("nome_loja", models.CharField(max_length=19)),
            ],
        ),
    ]
