# Generated by Django 4.1.5 on 2023-01-26 15:31

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Transacao",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "tipo",
                    models.CharField(
                        choices=[
                            ("Débito", " 1"),
                            ("Boleto", " 2"),
                            ("Financiamento", " 3"),
                            ("Crédito", " 4"),
                            ("Recebimento", " 5"),
                            ("Vendas", " 6"),
                            ("Recebimnto TED", " 7"),
                            ("Recebimento DOC", " 8"),
                            ("Aluguel", " 9"),
                        ],
                        max_length=15,
                    ),
                ),
                ("data", models.DateField(max_length=8)),
                ("valor", models.IntegerField()),
                ("cpf", models.CharField(max_length=11)),
                ("cartao", models.CharField(max_length=12)),
                ("hora", models.CharField(max_length=6)),
                ("dono_da_loja", models.CharField(max_length=14)),
                ("nome_loja", models.CharField(max_length=19)),
            ],
        ),
    ]
